package HealthcareLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseConstraintsAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class ConstraintsAspectDescriptor extends BaseConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }

  @Override
  public ConstraintsDescriptor getConstraints(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return new Appoinment_Constraints();
      case 1:
        return new Department_Constraints();
      case 2:
        return new Qualification_Constraints();
      default:
    }
    return new BaseConstraintsDescriptor(concept);
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a023fL), MetaIdFactory.conceptId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0273L), MetaIdFactory.conceptId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0280L)).seal();
}
