package HealthcareLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Appoinment_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new EducationalInstitute_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Employee_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new HealthcareSystem_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Hospital_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Patient_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new EmployeeRole_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a023fL), MetaIdFactory.conceptId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0284L), MetaIdFactory.conceptId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0279L), MetaIdFactory.conceptId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x1c392c4f11e2fc6cL), MetaIdFactory.conceptId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a028bL), MetaIdFactory.conceptId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0296L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0275L)).seal();
}
