package HealthcareLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AppoinmentStatus extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AppoinmentStatus() {
    super(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0244L, "AppoinmentStatus", "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480260");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Booked_0 = new EnumerationDescriptor.MemberDescriptor("Booked", "Booked", 0x2f557f2e960a0245L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480261");
  private final EnumerationDescriptor.MemberDescriptor myMember_Arrived_0 = new EnumerationDescriptor.MemberDescriptor("Arrived", "Arrived", 0x2f557f2e960a0246L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480262");
  private final EnumerationDescriptor.MemberDescriptor myMember_Fulfilled_0 = new EnumerationDescriptor.MemberDescriptor("Fulfilled", "Fulfilled", 0x2f557f2e960a0247L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480263");
  private final EnumerationDescriptor.MemberDescriptor myMember_Cancelled_0 = new EnumerationDescriptor.MemberDescriptor("Cancelled", "Cancelled", 0x2f557f2e960a0248L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480264");
  private final EnumerationDescriptor.MemberDescriptor myMember_NoShow_0 = new EnumerationDescriptor.MemberDescriptor("NoShow", "NoShow", 0x2f557f2e960a0249L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480265");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0244L, 0x2f557f2e960a0245L, 0x2f557f2e960a0246L, 0x2f557f2e960a0247L, 0x2f557f2e960a0248L, 0x2f557f2e960a0249L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Booked_0, myMember_Arrived_0, myMember_Fulfilled_0, myMember_Cancelled_0, myMember_NoShow_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Booked_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Booked":
        return myMember_Booked_0;
      case "Arrived":
        return myMember_Arrived_0;
      case "Fulfilled":
        return myMember_Fulfilled_0;
      case "Cancelled":
        return myMember_Cancelled_0;
      case "NoShow":
        return myMember_NoShow_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
