package HealthcareLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_EmployeeSpecialty extends EnumerationDescriptorBase {

  public EnumerationDescriptor_EmployeeSpecialty() {
    super(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a025aL, "EmployeeSpecialty", "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480282");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Cardiology_0 = new EnumerationDescriptor.MemberDescriptor("Cardiology", "Cardiology", 0x2f557f2e960a025cL, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480284");
  private final EnumerationDescriptor.MemberDescriptor myMember_Dermatology_0 = new EnumerationDescriptor.MemberDescriptor("Dermatology", "Dermatology", 0x2f557f2e960a025bL, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480283");
  private final EnumerationDescriptor.MemberDescriptor myMember_Neurology_0 = new EnumerationDescriptor.MemberDescriptor("Neurology", "Neurology", 0x2f557f2e960a025dL, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480285");
  private final EnumerationDescriptor.MemberDescriptor myMember_Pediatry_0 = new EnumerationDescriptor.MemberDescriptor("Pediatry", "Pediatry", 0x2f557f2e960a025eL, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480286");
  private final EnumerationDescriptor.MemberDescriptor myMember_NA_0 = new EnumerationDescriptor.MemberDescriptor("NA", "NA", 0x2f557f2e960a025fL, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480287");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a025aL, 0x2f557f2e960a025cL, 0x2f557f2e960a025bL, 0x2f557f2e960a025dL, 0x2f557f2e960a025eL, 0x2f557f2e960a025fL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Cardiology_0, myMember_Dermatology_0, myMember_Neurology_0, myMember_Pediatry_0, myMember_NA_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_NA_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Cardiology":
        return myMember_Cardiology_0;
      case "Dermatology":
        return myMember_Dermatology_0;
      case "Neurology":
        return myMember_Neurology_0;
      case "Pediatry":
        return myMember_Pediatry_0;
      case "NA":
        return myMember_NA_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
