package HealthcareLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ConditionStatus extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ConditionStatus() {
    super(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0255L, "ConditionStatus", "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480277");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Active_0 = new EnumerationDescriptor.MemberDescriptor("Active", "Active", 0x2f557f2e960a0256L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480278");
  private final EnumerationDescriptor.MemberDescriptor myMember_Recurrence_0 = new EnumerationDescriptor.MemberDescriptor("Recurrence", "Recurrence", 0x2f557f2e960a0257L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480279");
  private final EnumerationDescriptor.MemberDescriptor myMember_Inactive_0 = new EnumerationDescriptor.MemberDescriptor("Inactive", "Inactive", 0x2f557f2e960a0258L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480280");
  private final EnumerationDescriptor.MemberDescriptor myMember_Resolved_0 = new EnumerationDescriptor.MemberDescriptor("Resolved", "Resolved", 0x2f557f2e960a0259L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480281");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0255L, 0x2f557f2e960a0256L, 0x2f557f2e960a0257L, 0x2f557f2e960a0258L, 0x2f557f2e960a0259L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Active_0, myMember_Recurrence_0, myMember_Inactive_0, myMember_Resolved_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Active_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Active":
        return myMember_Active_0;
      case "Recurrence":
        return myMember_Recurrence_0;
      case "Inactive":
        return myMember_Inactive_0;
      case "Resolved":
        return myMember_Resolved_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
