package HealthcareLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Role extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Role() {
    super(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0266L, "Role", "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480294");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Doctor_0 = new EnumerationDescriptor.MemberDescriptor("Doctor", "Doctor", 0x2f557f2e960a0267L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480295");
  private final EnumerationDescriptor.MemberDescriptor myMember_Nurse_0 = new EnumerationDescriptor.MemberDescriptor("Nurse", "Nurse", 0x2f557f2e960a0268L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480296");
  private final EnumerationDescriptor.MemberDescriptor myMember_Pharmacist_0 = new EnumerationDescriptor.MemberDescriptor("Pharmacist", "Pharmacist", 0x2f557f2e960a0269L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480297");
  private final EnumerationDescriptor.MemberDescriptor myMember_HospitalManager_0 = new EnumerationDescriptor.MemberDescriptor("HospitalManager", "HospitalManager", 0x2f557f2e960a026aL, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480298");
  private final EnumerationDescriptor.MemberDescriptor myMember_Janitor_0 = new EnumerationDescriptor.MemberDescriptor("Janitor", "Janitor", 0x2f557f2e960a026bL, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480299");
  private final EnumerationDescriptor.MemberDescriptor myMember_Intern_0 = new EnumerationDescriptor.MemberDescriptor("Intern", "Intern", 0x2f557f2e960a026cL, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480300");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0266L, 0x2f557f2e960a0267L, 0x2f557f2e960a0268L, 0x2f557f2e960a0269L, 0x2f557f2e960a026aL, 0x2f557f2e960a026bL, 0x2f557f2e960a026cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Doctor_0, myMember_Nurse_0, myMember_Pharmacist_0, myMember_HospitalManager_0, myMember_Janitor_0, myMember_Intern_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Doctor_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Doctor":
        return myMember_Doctor_0;
      case "Nurse":
        return myMember_Nurse_0;
      case "Pharmacist":
        return myMember_Pharmacist_0;
      case "HospitalManager":
        return myMember_HospitalManager_0;
      case "Janitor":
        return myMember_Janitor_0;
      case "Intern":
        return myMember_Intern_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
