package HealthcareLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AppointmentType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AppointmentType() {
    super(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a024bL, "AppointmentType", "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480267");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Routine_0 = new EnumerationDescriptor.MemberDescriptor("Routine", "Routine", 0x2f557f2e960a024cL, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480268");
  private final EnumerationDescriptor.MemberDescriptor myMember_Walking_0 = new EnumerationDescriptor.MemberDescriptor("Walking", "Walking", 0x2f557f2e960a024dL, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480269");
  private final EnumerationDescriptor.MemberDescriptor myMember_Checkup_0 = new EnumerationDescriptor.MemberDescriptor("Checkup", "Checkup", 0x2f557f2e960a024eL, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480270");
  private final EnumerationDescriptor.MemberDescriptor myMember_Followup_0 = new EnumerationDescriptor.MemberDescriptor("Followup", "Followup", 0x2f557f2e960a024fL, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480271");
  private final EnumerationDescriptor.MemberDescriptor myMember_Emergency_0 = new EnumerationDescriptor.MemberDescriptor("Emergency", "Emergency", 0x2f557f2e960a0250L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480272");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a024bL, 0x2f557f2e960a024cL, 0x2f557f2e960a024dL, 0x2f557f2e960a024eL, 0x2f557f2e960a024fL, 0x2f557f2e960a0250L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Routine_0, myMember_Walking_0, myMember_Checkup_0, myMember_Followup_0, myMember_Emergency_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Routine_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Routine":
        return myMember_Routine_0;
      case "Walking":
        return myMember_Walking_0;
      case "Checkup":
        return myMember_Checkup_0;
      case "Followup":
        return myMember_Followup_0;
      case "Emergency":
        return myMember_Emergency_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
