package HealthcareLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ObservationType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ObservationType() {
    super(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0261L, "ObservationType", "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480289");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_SpO2_0 = new EnumerationDescriptor.MemberDescriptor("SpO2", "SpO2", 0x2f557f2e960a0262L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480290");
  private final EnumerationDescriptor.MemberDescriptor myMember_BloodPressure_0 = new EnumerationDescriptor.MemberDescriptor("BloodPressure", "BloodPressure", 0x2f557f2e960a0263L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480291");
  private final EnumerationDescriptor.MemberDescriptor myMember_HeartRate_0 = new EnumerationDescriptor.MemberDescriptor("HeartRate", "HeartRate", 0x2f557f2e960a0264L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480292");
  private final EnumerationDescriptor.MemberDescriptor myMember_XRay_0 = new EnumerationDescriptor.MemberDescriptor("XRay", "XRay", 0x2f557f2e960a0265L, "r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480293");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0261L, 0x2f557f2e960a0262L, 0x2f557f2e960a0263L, 0x2f557f2e960a0264L, 0x2f557f2e960a0265L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_SpO2_0, myMember_BloodPressure_0, myMember_HeartRate_0, myMember_XRay_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "SpO2":
        return myMember_SpO2_0;
      case "BloodPressure":
        return myMember_BloodPressure_0;
      case "HeartRate":
        return myMember_HeartRate_0;
      case "XRay":
        return myMember_XRay_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
