package HealthcareLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAppoinment = createDescriptorForAppoinment();
  /*package*/ final ConceptDescriptor myConceptCondition = createDescriptorForCondition();
  /*package*/ final ConceptDescriptor myConceptDepartment = createDescriptorForDepartment();
  /*package*/ final ConceptDescriptor myConceptEducationalInstitute = createDescriptorForEducationalInstitute();
  /*package*/ final ConceptDescriptor myConceptEmployee = createDescriptorForEmployee();
  /*package*/ final ConceptDescriptor myConceptEmployeeRole = createDescriptorForEmployeeRole();
  /*package*/ final ConceptDescriptor myConceptHealthcareSystem = createDescriptorForHealthcareSystem();
  /*package*/ final ConceptDescriptor myConceptHospital = createDescriptorForHospital();
  /*package*/ final ConceptDescriptor myConceptObservation = createDescriptorForObservation();
  /*package*/ final ConceptDescriptor myConceptOrganization = createDescriptorForOrganization();
  /*package*/ final ConceptDescriptor myConceptPatient = createDescriptorForPatient();
  /*package*/ final ConceptDescriptor myConceptPerson = createDescriptorForPerson();
  /*package*/ final ConceptDescriptor myConceptQualification = createDescriptorForQualification();
  /*package*/ final ConceptDescriptor myConceptSpecialty = createDescriptorForSpecialty();
  /*package*/ final EnumerationDescriptor myEnumerationAppoinmentStatus = new EnumerationDescriptor_AppoinmentStatus();
  /*package*/ final EnumerationDescriptor myEnumerationAppointmentType = new EnumerationDescriptor_AppointmentType();
  /*package*/ final EnumerationDescriptor myEnumerationConditionSeverity = new EnumerationDescriptor_ConditionSeverity();
  /*package*/ final EnumerationDescriptor myEnumerationConditionStatus = new EnumerationDescriptor_ConditionStatus();
  /*package*/ final EnumerationDescriptor myEnumerationEmployeeSpecialty = new EnumerationDescriptor_EmployeeSpecialty();
  /*package*/ final EnumerationDescriptor myEnumerationObservationType = new EnumerationDescriptor_ObservationType();
  /*package*/ final EnumerationDescriptor myEnumerationRole = new EnumerationDescriptor_Role();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAppoinment, myConceptCondition, myConceptDepartment, myConceptEducationalInstitute, myConceptEmployee, myConceptEmployeeRole, myConceptHealthcareSystem, myConceptHospital, myConceptObservation, myConceptOrganization, myConceptPatient, myConceptPerson, myConceptQualification, myConceptSpecialty);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Appoinment:
        return myConceptAppoinment;
      case LanguageConceptSwitch.Condition:
        return myConceptCondition;
      case LanguageConceptSwitch.Department:
        return myConceptDepartment;
      case LanguageConceptSwitch.EducationalInstitute:
        return myConceptEducationalInstitute;
      case LanguageConceptSwitch.Employee:
        return myConceptEmployee;
      case LanguageConceptSwitch.EmployeeRole:
        return myConceptEmployeeRole;
      case LanguageConceptSwitch.HealthcareSystem:
        return myConceptHealthcareSystem;
      case LanguageConceptSwitch.Hospital:
        return myConceptHospital;
      case LanguageConceptSwitch.Observation:
        return myConceptObservation;
      case LanguageConceptSwitch.Organization:
        return myConceptOrganization;
      case LanguageConceptSwitch.Patient:
        return myConceptPatient;
      case LanguageConceptSwitch.Person:
        return myConceptPerson;
      case LanguageConceptSwitch.Qualification:
        return myConceptQualification;
      case LanguageConceptSwitch.Specialty:
        return myConceptSpecialty;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationAppoinmentStatus, myEnumerationAppointmentType, myEnumerationConditionSeverity, myEnumerationConditionStatus, myEnumerationEmployeeSpecialty, myEnumerationObservationType, myEnumerationRole);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAppoinment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HealthcareLanguage", "Appoinment", 0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a023fL);
    b.class_(false, false, true);
    b.origin("r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480255");
    b.version(3);
    b.property("start", 0x2f557f2e960a0240L).type(PrimitiveTypeId.STRING).origin("3410772130865480256").done();
    b.property("end", 0x2f557f2e960a0241L).type(PrimitiveTypeId.STRING).origin("3410772130865480257").done();
    b.property("status", 0x2f557f2e960a0242L).type(MetaIdFactory.dataTypeId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0244L)).origin("3410772130865480258").done();
    b.property("type", 0x2f557f2e960a0243L).type(MetaIdFactory.dataTypeId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a024bL)).origin("3410772130865480259").done();
    b.associate("practitioner", 0x2f557f2e960a029bL).target(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0279L).optional(true).origin("3410772130865480347").done();
    b.aggregate("patient", 0x2f557f2e960a029aL).target(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0296L).optional(true).ordered(true).multiple(false).origin("3410772130865480346").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCondition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HealthcareLanguage", "Condition", 0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a026eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480302");
    b.version(3);
    b.property("status", 0x2f557f2e960a0270L).type(MetaIdFactory.dataTypeId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0255L)).origin("3410772130865480304").done();
    b.property("severity", 0x2f557f2e960a0271L).type(MetaIdFactory.dataTypeId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0251L)).origin("3410772130865480305").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDepartment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HealthcareLanguage", "Department", 0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0273L);
    b.class_(false, false, false);
    // extends: HealthcareLanguage.structure.Organization
    b.super_(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a023dL);
    b.origin("r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480307");
    b.version(3);
    b.aggregate("staff", 0x2f557f2e960a0274L).target(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0275L).optional(true).ordered(true).multiple(true).origin("3410772130865480308").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEducationalInstitute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HealthcareLanguage", "EducationalInstitute", 0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0284L);
    b.class_(false, false, true);
    // extends: HealthcareLanguage.structure.Organization
    b.super_(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a023dL);
    b.origin("r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480324");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEmployee() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HealthcareLanguage", "Employee", 0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0279L);
    b.class_(false, false, false);
    // extends: HealthcareLanguage.structure.Person
    b.super_(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a027aL);
    b.origin("r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480313");
    b.version(3);
    b.property("description", 0x2f557f2e960a027eL).type(PrimitiveTypeId.STRING).origin("3410772130865480318").done();
    b.aggregate("qualifications", 0x2f557f2e960a027fL).target(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0280L).optional(true).ordered(true).multiple(true).origin("3410772130865480319").done();
    b.aggregate("specialty", 0x2f95f283bc9898dbL).target(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f95f283bc9898d9L).optional(true).ordered(true).multiple(true).origin("3428913338931255515").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEmployeeRole() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HealthcareLanguage", "EmployeeRole", 0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0275L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480309");
    b.version(3);
    b.property("role", 0x2f557f2e960a0277L).type(MetaIdFactory.dataTypeId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0266L)).origin("3410772130865480311").done();
    b.aggregate("employee", 0x2f557f2e960a0278L).target(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0279L).optional(false).ordered(true).multiple(false).origin("3410772130865480312").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHealthcareSystem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HealthcareLanguage", "HealthcareSystem", 0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f95f283bc994d0aL);
    b.class_(false, false, false);
    b.origin("r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3428913338931301642");
    b.version(3);
    b.aggregate("elements", 0x2f95f283bc994d0bL).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL).optional(true).ordered(true).multiple(true).origin("3428913338931301643").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHospital() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HealthcareLanguage", "Hospital", 0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a028bL);
    b.class_(false, false, true);
    // extends: HealthcareLanguage.structure.Organization
    b.super_(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a023dL);
    b.origin("r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480331");
    b.version(3);
    b.property("description", 0x2f557f2e960a028dL).type(PrimitiveTypeId.STRING).origin("3410772130865480333").done();
    b.aggregate("departments", 0x2f557f2e960a028eL).target(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0273L).optional(true).ordered(true).multiple(true).origin("3410772130865480334").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForObservation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HealthcareLanguage", "Observation", 0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0290L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480336");
    b.version(3);
    b.property("value", 0x2f557f2e960a0291L).type(PrimitiveTypeId.STRING).origin("3410772130865480337").done();
    b.property("type", 0x2f557f2e960a0292L).type(MetaIdFactory.dataTypeId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0261L)).origin("3410772130865480338").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOrganization() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HealthcareLanguage", "Organization", 0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a023dL);
    b.class_(false, true, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480253");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPatient() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HealthcareLanguage", "Patient", 0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0296L);
    b.class_(false, false, false);
    // extends: HealthcareLanguage.structure.Person
    b.super_(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a027aL);
    b.origin("r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480342");
    b.version(3);
    b.aggregate("observation", 0x2f557f2e960a0297L).target(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0290L).optional(true).ordered(true).multiple(true).origin("3410772130865480343").done();
    b.aggregate("condition", 0x2f557f2e960a0298L).target(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a026eL).optional(true).ordered(true).multiple(true).origin("3410772130865480344").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPerson() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HealthcareLanguage", "Person", 0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a027aL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480314");
    b.version(3);
    b.property("gender", 0x2f557f2e960a027cL).type(PrimitiveTypeId.BOOLEAN).origin("3410772130865480316").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForQualification() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HealthcareLanguage", "Qualification", 0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0280L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3410772130865480320");
    b.version(3);
    b.property("issueDate", 0x2f557f2e960a0282L).type(PrimitiveTypeId.STRING).origin("3410772130865480322").done();
    b.associate("issuer", 0x2f557f2e960a0283L).target(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a0284L).optional(true).origin("3410772130865480323").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSpecialty() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HealthcareLanguage", "Specialty", 0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f95f283bc9898d9L);
    b.class_(false, false, false);
    b.origin("r:e5bcaa7d-12f5-4ff3-b8b6-1218c56a72be(HealthcareLanguage.structure)/3428913338931255513");
    b.version(3);
    b.property("name", 0x2f95f283bc9898daL).type(MetaIdFactory.dataTypeId(0x7f0568a28c1a4091L, 0xa87e390be85922c7L, 0x2f557f2e960a025aL)).origin("3428913338931255514").done();
    return b.create();
  }
}
